stages:
  - test
  - reminder

test:
  tags:
    - golang:1.14
  stage: test
  except:
    - schedules
  script:
    - go test -v -cover ./...

reminder:
  tags:
    - golang:1.14
  stage: reminder
  only:
    - schedules
  before_script:
    - cd config && git init && git remote add origin "https://${GITLAB_RUNNER_NAME}:${GITLAB_API_ACCESS_TOKEN}@${CONFIG_REPOSITORY}" && git pull origin master
    - cd ../
  script:
    - go run main.go -cmd 2 -mtg 1
    - go run main.go -cmd 2 -mtg 2
