stages:
  - test
  - reminder

test:
  tags:
    - golang:1.14
  stage: test
  except:
    - schedules
  before_script:
    - go get github.com/boumenot/gocover-cobertura
  script:
    - go test -v -cover ./...
    - go test -coverprofile=coverage.txt -covermode count github.com/gorilla/mux
    - gocover-cobertura < coverage.txt > coverage.xml

reminder:
  tags:
    - golang:1.14
  stage: reminder
  only:
    - schedules
  before_script:
    - git config --global http.sslVerify false
    - cd config
    - ls -la
    # git init が正常に動いていないと? fatal: remote origin already exists. と言われるので注意
    - >
      if [ -e ./.git ]; then
        rm -rf .git
      fi
    - ls -la
    - git init
    - git remote add origin "https://${MAIL_REMINDER_NAME}:${MAIL_REMINDER_ACCESS_TOKEN}@${CONFIG_REPOSITORY#*@}"
    - git pull origin master
    - cd ../
  script:
    - go run main.go -cmd 2 -mtg 1
    - go run main.go -cmd 2 -mtg 2
